// Master
export const VIEW_ALL_INVOICE = 'VIEW_ALL_INVOICE';
export const VIEW_ALL_STMT = 'VIEW_ALL_STMT';
export const VIEW_ALL_PUR_HIST = 'VIEW_ALL_PUR_HIST';
export const VIEW_ALL_ONHAND_QTY = 'VIEW_ALL_ONHAND_QTY';
export const VIEW_ALL_INVENTORY = 'VIEW_ALL_INVENTORY';
export const VIEW_ALL_CUSTOMER = 'VIEW_ALL_CUSTOMER';

// Customer
export const VIEW_OWN_INVOICE = 'VIEW_OWN_INVOICE';
export const VIEW_OWN_STMT = 'VIEW_OWN_STMT';
export const VIEW_OWN_PUR_HIST = 'VIEW_OWN_PUR_HIST';

export const MAST_FUNC = [
  VIEW_ALL_INVOICE,
  VIEW_ALL_STMT,
  VIEW_ALL_PUR_HIST,
  VIEW_ALL_ONHAND_QTY,
  VIEW_ALL_INVENTORY,
  VIEW_ALL_CUSTOMER
];

export const CUST_FUNC = [
  VIEW_OWN_INVOICE, VIEW_OWN_STMT, VIEW_OWN_PUR_HIST
];
